### PR TITLE
Locks to 1 decimal place instead of infinite

### LINKED ISSUE #8278: Discover ratings don't have a limit on decimal places
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

14 decimal place precision on ratings

### Expected Behavior

To stop at 1 decimal place

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Ubuntu 22
- Radarr: 4.3.2.68.57
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 110
- Database: Sqlite 3.40.0
```

### What branch are you running?

Master

### Trace Logs?

image
image

### PR DESCRIPTION
**Pull request by Lagicrus**
#### Database Migration
NO

#### Description
Locks ratings for TMDB at 1 decimal place

#### Todos
- [x ] Tests
- [x ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #8278

### CODE REVIEW

**Comment by bakerboy448** [comment]
Would it be possible to use the component like was done in https://github.com/Radarr/Radarr/commit/0a77a13fa821a923186b1a973fec90b81e1e1522 for other pages instead of having different logic here?

File: frontend/src/DiscoverMovie/Overview/DiscoverMovieOverviewInfo.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ function getInfoRowProps(row, props) {
     return {
       title: translate('Ratings'),
       iconName: icons.HEART,
-      label: `${props.ratings.tmdb.value * 10}%`
+      label: `${(props.ratings.tmdb.value * 10).toFixed(1)}%`
```
Comment (Qstick) [inline frontend/src/DiscoverMovie/Overview/DiscoverMovieOverviewInfo.js:76]:
```suggestion
      label: `${(props.ratings.tmdb.value * 10).toFixed()}%`
```

Change to .toFixed() to align with other places in the UI that have no decimal places. Good after that

**Review by Qstick — CHANGES_REQUESTED** [review]
