### PR TITLE
Zeus UI fix

### LINKED ISSUE #6129: Pull Sonarr commit 'New: Calendar option for full color events'
Pull https://github.com/Sonarr/Sonarr/commit/0210b5c5c1b5c56dce6f4c9f3f56366adba950d3

```
git cherry-pick -ex 0210b5c5c1b5c56dce6f4c9f3f56366adba950d3
```

This commit has 7 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#656](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/656)

### PR DESCRIPTION
**Pull request by thezak48**
#### Database Migration
NO

#### Description
Fixup some UI Flashbangs, Color Impaired mode on Calendar and disabled label text

#### Todos
N/A

#### Issues Fixed or Closed by this PR

Fixes #6129

### CODE REVIEW

File: frontend/src/Calendar/Options/CalendarOptionsModalContent.js [hunk 1]
```diff
@@ -136,6 +139,18 @@ class CalendarOptionsModalContent extends Component {
                   onChange={this.onOptionInputChange}
                 />
               </FormGroup>
+
+              <FormGroup>
+                <FormLabel>Full Color Events</FormLabel>
```
Comment (Qstick) [inline frontend/src/Calendar/Options/CalendarOptionsModalContent.js:144]:
```suggestion
                <FormLabel>{translate('FullColorEvents')}</FormLabel>
```

File: frontend/src/Calendar/Options/CalendarOptionsModalContent.js [hunk 2]
```diff
@@ -136,6 +139,18 @@ class CalendarOptionsModalContent extends Component {
...
+
+                <FormInputGroup
+                  type={inputTypes.CHECK}
+                  name="fullColorEvents"
+                  value={fullColorEvents}
+                  helpText="Altered style to color the entire event with the status color, instead of just the left edge. Does not apply to Agenda"
```
Comment (Qstick) [inline frontend/src/Calendar/Options/CalendarOptionsModalContent.js:150]:
```suggestion
                  helpText={translate('FullColorEventsHelpText')}
```

**Review by Qstick — CHANGES_REQUESTED** [review]
