### PR TITLE
Fixed: (UI) Show release dates when enabled

### LINKED ISSUE #8614: Pull Sonarr commit 'Fix showing sorting values, add tooltips and translations to SeriesIndexPoster'
Pull https://github.com/Sonarr/Sonarr/commit/f90bef69342ca896dc1e55589dc9cd37b953f8ae

```
git cherry-pick -ex f90bef69342ca896dc1e55589dc9cd37b953f8ae
```

This commit has 4 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8637: Cinema release date and release not displayed again
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

cinema release and release dates no longer displayed while the display option is selected
image

image

it was supposed to be solved in version 4.5.2.7388 but the bug is still there

### Expected Behavior

that the dates are displayed again as before

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: windows 11
- Radarr: 4.5.2.7388
- Docker Install: no
- Using Reverse Proxy: no
- Browser: opera 99.0.4788.13
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

[logfile.txt](https://github.com/Radarr/Radarr/files/11593384/logfile.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* Fixes #8637
* Fixes #8614

### CODE REVIEW

File: frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx [hunk 1]
```diff
@@ -214,10 +230,41 @@ function MovieIndexPoster(props: MovieIndexPosterProps) {
...
+      {showReleaseDate && releaseDateType === 'Digital' ? (
+        <div className={styles.title}>
+          <Icon name={icons.MOVIE_FILE} />{' '}
+          {getRelativeDate(releaseDate, shortDateFormat, showRelativeDates, {
+            timeFormat,
+            timeForToday: false,
+          })}
+        </div>
+      ) : null}
+
```
Comment (RobinDadswell) [inline frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx:262]: Could we simplify this by using a variable for the icon name in so we only need this block once?

Comment (tifo71) [reply frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx:262]: @mynameisbogdan The problem has not been solved and is still present in the current version. the option is checked and dates are not displayed

image

**Review by Qstick — APPROVED** [review]

**Comment by Qstick** [comment]
Tested and working

File: frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx [hunk 2]
```diff
@@ -214,10 +233,33 @@ function MovieIndexPoster(props: MovieIndexPosterProps) {
...
+        <div className={styles.title}>
+          <Icon name={icons.IN_CINEMAS} />{' '}
+          {getRelativeDate(inCinemas, shortDateFormat, showRelativeDates, {
+            timeFormat,
+            timeForToday: false,
+          })}
+        </div>
+      ) : null}
+
+      {showReleaseDate && releaseDate && releaseDateType ? (
```
Comment (RobinDadswell) [inline frontend/src/Movie/Index/Posters/MovieIndexPoster.tsx:246]: I believe this would work as you would never get `releaseDate` without `releaseDateType` 

```suggestion
      {showReleaseDate && releaseDate ? (
```

**Review by RobinDadswell — CHANGES_REQUESTED** [review]

**Review by RobinDadswell — APPROVED** [review]
