### PR TITLE
Fix issue with images stacking on the movie details page

### LINKED ISSUE #4653: Set min-width on MovieDetails Files action column
**Describe the bug**
221C2F83-38A1-46D8-8513-5704FC58AC56

Shouldn’t wrap

### PR DESCRIPTION
**Pull request by austinwbest**
#### Database Migration
 NO

#### Description
Title..

#### Issues Fixed or Closed by this PR
Fixes #4653

### CODE REVIEW

File: frontend/src/MovieFile/Editor/MovieFileEditorRow.js [hunk 1]
```diff
@@ -105,7 +105,7 @@ class MovieFileEditorRow extends Component {
     return (
       <TableRow>
         <TableRowCell
-          className={styles.relativePath}
+          className={styles.title}
```
Comment (Qstick) [inline frontend/src/MovieFile/Editor/MovieFileEditorRow.js:108]: I'd say change it back here and fix it on the css side. That way it jives with property name.

Comment (austinwbest) [reply frontend/src/MovieFile/Editor/MovieFileEditorRow.js:108]: It doesn't jive with the UI is why i swapped it lol.. But sure.
