### PR TITLE
Fixed: '/movie' URL Base breaking UI navigation

### LINKED ISSUE #5555: Pull Sonarr commit 'Fixed: '/series' URL Base breaking UI navigation'
Pull https://github.com/Sonarr/Sonarr/commit/cc39d4ee23b7d49abd883256ff0ddc5dcefe9161

```
git cherry-pick -ex cc39d4ee23b7d49abd883256ff0ddc5dcefe9161
```

This commit has 2 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #5603: URL Base /movie conflict
URL Base /movie conflicts with opening a movie item wich results in You must be lost, nothing to see here.
This was not an issue in the previous radarr before the new ui look
This bug is not present in latest sonarr v3

no url base
http://xxx/movie/xxx

url base /test
http://xxx/test/movie/xxx

url base /movie
http://xxx/movie/xxx

You must be lost, nothing to see here.
Manually changing to http://xxx/movie/movie/xxx does open the item.

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
tested...works
#### Todos
- [ ] Tests N/A
- [ ] Translation Keys N/A
- [ ] Wiki Updates N/A

#### Issues Fixed or Closed by this PR

* Fixes #5603
* Fixes #5555

### CODE REVIEW

File: frontend/src/Components/Link/Link.js [hunk 1]
```diff
@@ -47,11 +47,7 @@ class Link extends Component {
         el = 'a';
         linkProps.href = to;
         linkProps.target = target || '_self';
-      } else if (to.startsWith(`${window.Radarr.urlBase}/`)) {
-        el = RouterLink;
-        linkProps.to = to;
-        linkProps.target = target;
-      } else {
+        } else {
```
Comment (Qstick) [inline frontend/src/Components/Link/Link.js:50]: fix the indentation here

Comment (bakerboy448) [reply frontend/src/Components/Link/Link.js:50]: you're slacking missed one (other file, line 56); lint caught to...i suppose it helps to actually lint it
