### PR TITLE
Loads only request movie first into full collection. Should fix things.

### LINKED ISSUE #982: Calendar: Links to movies does not work
**Description:**

In the calendar when clicking on a movie it ends up in a 404

**Radarr Version:**

0.2.0.426

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

### PR DESCRIPTION
**Pull request by galli-leo**
Fixes #982

### CODE REVIEW

File: src/UI/Movies/FullMovieCollection.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 var movieCollection = require('./MoviesCollection');
 
 var fullCollection = movieCollection.clone();
+fullCollection.reset();
```
Comment (fedoranimus) [inline src/UI/Movies/FullMovieCollection.js]: Doesn't think do the same thing as the the fetch 3 lines down?

Comment (galli-leo) [inline src/UI/Movies/FullMovieCollection.js]: @fedoranimus No because then Movie Controller thinks you have more than 0 models (since it has the 25 from the first page still) which causes 404s.

**Comment by geogolem** [comment]
I tried to also push another commit to this PR.. but I messed up (dont know what happened). but I ended up with this: https://github.com/Radarr/Radarr/pull/1056/commits/b2857474013e965ee5d81bb73923aab83d669d75

File: src/UI/Movies/FullMovieCollection.js (hunk 1 above)
Comment (geogolem) [inline src/UI/Movies/FullMovieCollection.js]: when you do this reset isnt the first page fetched?

Comment (geogolem) [inline src/UI/Movies/FullMovieCollection.js]: Im not sure I totally understand what this does but I dont see any problems with it.
