### PR TITLE
Manual import ts

### LINKED ISSUE #8296: Pull Sonarr commit 'Convert Manual Import to Typescript'
Pull https://github.com/Sonarr/Sonarr/commit/defdc84b7ee1dae0ecbfec7590534684afe893b0

```
git cherry-pick -ex defdc84b7ee1dae0ecbfec7590534684afe893b0
```

This commit has 31 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8303: Pull Sonarr commit 'Fixed: Import mode for manually imported queue items'
Pull https://github.com/Sonarr/Sonarr/commit/3dce7e729c59735f99a4e1f71e3dff70534fcf94

```
git cherry-pick -ex 3dce7e729c59735f99a4e1f71e3dff70534fcf94
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8304: Pull Sonarr commit 'Fixed: Override and Grab release with unknown series'
Pull https://github.com/Sonarr/Sonarr/commit/221bb10261aa0b2b573e661bc587316a6173fe0f

```
git cherry-pick -ex 221bb10261aa0b2b573e661bc587316a6173fe0f
```

This commit has 4 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8305: Pull Sonarr commit 'Fixed: Series index not loading'
Pull https://github.com/Sonarr/Sonarr/commit/835910843b7866c673a5876d537bd94e42c1a8a8

```
git cherry-pick -ex 835910843b7866c673a5876d537bd94e42c1a8a8
```

This commit has 2 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8318: Pull Sonarr commit 'Typings cleanup and improvements'
Pull https://github.com/Sonarr/Sonarr/commit/b2c43fb2a67965d68d3d35b72302b0cddb5aca23

```
git cherry-pick -ex b2c43fb2a67965d68d3d35b72302b0cddb5aca23
```

This commit has 75 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8321: Pull Sonarr commit 'Fixed: Series selection unselecting on mobile browsers'
Pull https://github.com/Sonarr/Sonarr/commit/513b746fc3ff285f617389483401cb99c05c3359

```
git cherry-pick -ex 513b746fc3ff285f617389483401cb99c05c3359
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8323: Pull Sonarr commit 'Appease linter'
Pull https://github.com/Sonarr/Sonarr/commit/3b5e83670b844cf7c20bf7d744d9fbc96fde6902

```
git cherry-pick -ex 3b5e83670b844cf7c20bf7d744d9fbc96fde6902
```

This commit has 4 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #8425: Manual Import of Movies just spins forever when attempting to enumerate movie list
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually importing a movie, when the file name window opens, then clicking movie to match it, the movie list enumeration just spins with no movies ever populating.

### Expected Behavior

Movies populate so you can select one

### Steps To Reproduce

1. Go to Movies.
2. Click "Manual Import"
3. Select a folder with a movie file within
4. Click Interactive Import
5. To the right of the filename, click "Movie" to match the file with a movie.
6. In the next window where movies are supposed to be listed, the window will just spin forever. I've left it here for up to 10m without anything changing.

### Environment

```markdown
- OS: Ubuntu 18.04
- Radarr: I have tried with 4.5.1.7166 and 4.5.1.7171
- Docker Install: linuxserver.io nightly container
- Using Reverse Proxy: Yes, nginx + ssl
- Browser: Chrome 64 bit
- Database: Sqlite 3.40.1
```

### What branch are you running?

Nightly

### Trace Logs?
[radarr.trace.submit.txt](https://github.com/Radarr/Radarr/files/11366348/radarr.trace.submit.txt)

In the trace log, I attemped to use a 20/20 episode file for manual import (I know it's not a movie, but it was readily available in my temp folder to reproduce the issue.)

### LINKED ISSUE #8446: Mobile - Scrolling on Movie Index in Edit clears selected
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Movie Index => Table Mode => enable movie editor and select movies => scroll => selections are cleared

### Expected Behavior

Selections should not be cleared

### Steps To Reproduce

See above

### Environment

```markdown
- OS: agnostic
- Radarr: 4.5.1.7194
- Docker Install: agnostic
- Using Reverse Proxy: Yes
- Browser: chrome iOS 112.0.5615.167
- Database: agnostic
```

### What branch are you running?

Nightly

### Trace Logs?

N/A UI
Non-issue on Sonarr 4.0.0.471

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
TS for Manual Import

#### Todos
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)

#### Issues Fixed or Closed by this PR

* Fixes #8296 
* Fixes #8303
* Fixes #8304 
* Fixes #8305 
* Fixes #8318 
* Fixes #8321 
* Fixes #8323 
* Fixes #8425
* Fixes #8446

### CODE REVIEW

File: frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx [hunk 1]
```diff
@@ -0,0 +1,361 @@
...
+      />
+
+      <TableRowCell className={styles.relativePath} title={relativePath}>
+        {relativePath}
+      </TableRowCell>
+
+      {isMovieColumnVisible ? (
+        <TableRowCellButton
+          isDisabled={!allowMovieChange}
+          title={allowMovieChange ? 'Click to change movie' : undefined}
```
Comment (bakerboy448) [inline frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx:244]:
```suggestion
          title={allowMovieChange ? translate('ClickToChangeMovie') : undefined}
```

File: frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx [hunk 2]
```diff
@@ -0,0 +1,361 @@
...
+        {showReleaseGroupPlaceholder ? (
+          <InteractiveImportRowCellPlaceholder isOptional={true} />
+        ) : (
+          releaseGroup
+        )}
+      </TableRowCellButton>
+
+      <TableRowCellButton
+        className={styles.quality}
+        title="Click to change quality"
```
Comment (bakerboy448) [inline frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx:268]: Ditto
